import { StatusCodes } from 'http-status-codes';

const transValidation = {
  SERVER_INCORRECT: 'Something went wrong, please wait !!!',
  UPLOAD_INCORRECT: 'Upload image failed, please check your image size !!!',
  INPUT_CORRECT: 'Successfully!!',
  EMAIL_EXIST: 'Email existed!!!',
  EMAIL_NOT_EXIST: 'Email does not exist!!!',
  CONVERSATION_EXIST: 'Conversation already exists',
  USER_NAME_EXIST: 'User name existed!!!',
  CONVERSATION_NOT_FOUND: 'Conversation not found',
  LOGIN_FAIL: 'Login information is incorrect!!!',
  REGISTER_FAIL: 'Register failed!!!',
  ADMIN_FAIL: 'You do not have permission !!!',
  OTP_FAIL: 'OTP is not correct !!!',
  OTP_EXPIRED_TIMEOUT: 'OTP expired !!!',
  IMAGE_FAIL: 'You did not select any image !!!',
  NOT_FOUND: 'Not found!!!',
  USER_NOT_EXIST: 'User does not exist!!!',
  UPLOAD_CORRECT: 'Upload successful',
  CHANGE_PASSWORD_CORRECT: 'Password changed successfully',
  PASSWORD_FAIL: 'Password incorrect, please check again',
  NOT_LOGIN: 'You are not logged in, please login to the system!',
  ACCESS_TOKEN: 'Access token expired or invalid',
  INVALID_TOKEN: 'Token invalid',
  EXPIRED_TOKEN: 'Token expired',
  BAD_REQUEST: 'Bad request',
  FETCH_SUCCESS: 'Fetch data successfully',
  CREATE_SUCCESS: 'Create data successfully',
  UPDATE_SUCCESS: 'Update data successfully',
  DELETE_SUCCESS: 'Delete data successfully',
  MISSING_SERVER_ID: 'Missing server ID',
  MISSING_CHANNEL_NAME: 'Missing channel Name',
};
const errorCode = {
  SERVER_INCORRECT: 'server_incorrect',
  UPLOAD_INCORRECT: 'upload_incorrect',
  INPUT_CORRECT: 'input_correct',
  EMAIL_EXIST: 'email_exist',
  IDENTITY_EXIST: 'identity_exist',
  PHONE_EXIST: 'phone_exist',
  LOGIN_FAIL: 'login_fail',
  REGISTER_FAIL: 'register_fail',
  ADMIN_FAIL: 'admin_fail',
  OTP_FAIL: 'otp_fail',
  OTP_EXPIRED_TIMEOUT: 'otp_expired_timeout',
  IMAGE_FAIL: 'image_fail',
  NOT_FOUND: 'not_found',
  UPLOAD_CORRECT: 'upload_correct',
  CHANGE_PASSWORD_CORRECT: 'change_password_correct',
  PASSWORD_FAIL: 'password_fail',
  NOT_LOGIN: 'not_login',
  ACCESS_TOKEN: 'access_token',
  INVALID_TOKEN: 'invalid_token',
  EXPIRED_TOKEN: 'expired_token',
  INVALID_ADDRESS: 'invalid_address',
  BAD_REQUEST: 'bad_request',
  USER_NOT_EXIST: 'user_not_exist',
  MISSING_SERVER_ID: 'missing_server_id',
  MISSING_CHANNEL_ID: 'missing_channel_id',
  EXIST_CHANNEL_NAME: 'exist_channel_name',
  NO_TOKEN: 'no_token',
  FORBIDDEN: 'forbidden',
  WRONG_PASSWORD: 'wrong_password',
  ERROR_DELETE_MEMBER: 'error_delete_member',
  UPDATE_USER_FAIL: 'update_user_fail',
};

const responseStatus = {
  SUCCESS: StatusCodes.OK,
  CREATED: StatusCodes.CREATED,
  BAD_REQUEST: StatusCodes.BAD_REQUEST,
  UNAUTHORIZED: StatusCodes.UNAUTHORIZED,
  FORBIDDEN: StatusCodes.FORBIDDEN,
  NOT_FOUND: StatusCodes.NOT_FOUND,
  INTERNAL_SERVER_ERROR: StatusCodes.INTERNAL_SERVER_ERROR,
  CONFLICT: StatusCodes.CONFLICT,
};

export default { transValidation, errorCode, responseStatus };
